### ISSUE TITLE
Is there a way to use ResNet?

### ISSUE THREAD

**Issue by lambdaofgod** [DeepRNN/image_captioning#46]
I was trying to run the model with ResNet as CNN. I've supplied model weights file in parameters, and also changed it in configuration. But in Tensorboard it still seems like the network still uses VGG.

Is there a way to actually use ResNet? If so, how?

**Comment by cynthia0811** [comment]
Did  you open  the webpage of ResNet50 or VGG16？I cannot open the it. Can you share your method?

**Comment by lambdaofgod** [comment]
When I open the page that is linked in README there is a download button, and it allows you to download weights.
